<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage
    xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="callisto"
    nsURI="http://inchron.com/callisto/0.1.0"
    nsPrefix="callisto">
  <eAnnotations
      source="http://www.eclipse.org/emf/2002/GenModel">
    <details
        key="copyrightText"
        value="Copyright (c) 2017-2024 INCHRON AG&#xA;&#xA;This program and the accompanying materials are made&#xA;available under the terms of the Eclipse Public License 2.0&#xA;which is available at https://www.eclipse.org/legal/epl-2.0/&#xA;&#xA;SPDX-License-Identifier: EPL-2.0&#xA;&#xA;Contributors:&#xA;  INCHRON AG - Metamodel design and implementation"/>
  </eAnnotations>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Accumulate"
      eSuperTypes="#//BinaryOperation">
    <eAnnotations
        source="http://www.eclipse.org/emf/2002/GenModel">
      <details
          key="documentation"
          value="When evaluated, the Accumulate Operation evaluates its two Operands and adds the result."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Benchmark"
      eSuperTypes="#//platform/ModelObject">
    <eAnnotations
        source="http://www.eclipse.org/emf/2002/GenModel">
      <details
          key="documentation"
          value="The Benchmark class aggregates the measurements of a specific benchmark program taken of different CoreType. It is usually representative for a certain Category."/>
    </eAnnotations>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="category"
        lowerBound="1"
        eType="#//Category"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="coreSpecificTimeDistributions"
        lowerBound="1"
        upperBound="-1"
        eType="#//CoreSpecificTimeDistribution"
        containment="true"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="BinaryOperation"
      abstract="true"
      eSuperTypes="#//Operation">
    <eAnnotations
        source="http://www.eclipse.org/emf/2002/GenModel">
      <details
          key="documentation"
          value="The BinaryOperation is an abstract class, which represents an Operation with two Operands."/>
    </eAnnotations>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="leftSide"
        lowerBound="1"
        eType="#//Operand"
        containment="true">
      <eAnnotations
          source="http://www.eclipse.org/emf/2002/GenModel">
        <details
            key="documentation"
            value="The Operand used on the left side of the Operation."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="rightSide"
        lowerBound="1"
        eType="#//Operand"
        containment="true">
      <eAnnotations
          source="http://www.eclipse.org/emf/2002/GenModel">
        <details
            key="documentation"
            value="The Operand used on the right side of the Operation."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Categorizable"
      abstract="true">
    <eAnnotations
        source="http://www.eclipse.org/emf/2002/GenModel">
      <details
          key="documentation"
          value="A Category represents a set of elements with common properties. Instances of EClasses derived from Categorizable can be assigned a Category."/>
    </eAnnotations>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="categorizations"
        upperBound="-1"
        eType="#//CategoryMapping"
        eOpposite="#//CategoryMapping/categorizables"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Category"
      eSuperTypes="#//platform/ModelObject">
    <eAnnotations
        source="http://www.eclipse.org/emf/2002/GenModel">
      <details
          key="documentation"
          value="A Category represents a set of common properties."/>
    </eAnnotations>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="coreSpecificAnnotations"
        eType="#//CoreSpecificAnnotations"
        containment="true">
      <eAnnotations
          source="http://www.eclipse.org/emf/2002/GenModel">
        <details
            key="documentation"
            value="Each Category has a list of CoreType specific annotations, which are used to detect if executable entities in a trace recorded on that CoreType should be assigned that Category."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="CategoryMapping"
      eSuperTypes="#//platform/ModelObject">
    <eAnnotations
        source="http://www.eclipse.org/emf/2002/GenModel">
      <details
          key="documentation"
          value="A CategoryMapping assigns a certain Category to a set of model elements, which must be derived from the EClass Categorizable. The list of CategoryMappings is usually part of the model."/>
    </eAnnotations>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="category"
        lowerBound="1"
        eType="#//Category"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="categorizables"
        upperBound="-1"
        eType="#//Categorizable"
        eOpposite="#//Categorizable/categorizations"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="ClusterReference">
    <eAnnotations
        source="http://www.eclipse.org/emf/2002/GenModel">
      <details
          key="documentation"
          value="The ClusterReference is used to define the containment of a set of ClusterTypes in another ClusterType."/>
    </eAnnotations>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="instanceCount"
        lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1">
      <eAnnotations
          source="http://www.eclipse.org/emf/2002/GenModel">
        <details
            key="documentation"
            value="The number of ClusterType instances this reference refers to."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="clusterType"
        eType="#//ClusterType">
      <eAnnotations
          source="http://www.eclipse.org/emf/2002/GenModel">
        <details
            key="documentation"
            value="The ClusterType this reference refers to."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="ClusterType"
      eSuperTypes="#//TypeDefinition">
    <eAnnotations
        source="http://www.eclipse.org/emf/2002/GenModel">
      <details
          key="documentation"
          value="The ClusterType defines the structure of a complete processor, SoC or of an arbitrary subset. Examples are S32Z2 or its Real-Time Units."/>
    </eAnnotations>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="subClusters"
        upperBound="-1"
        eType="#//ClusterReference"
        containment="true">
      <eAnnotations
          source="http://www.eclipse.org/emf/2002/GenModel">
        <details
            key="documentation"
            value="The sub-clusters contained in this ClusterType."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="cores"
        upperBound="-1"
        eType="#//CoreReference"
        containment="true">
      <eAnnotations
          source="http://www.eclipse.org/emf/2002/GenModel">
        <details
            key="documentation"
            value="The cores contained in this ClusterType."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Constant"
      eSuperTypes="#//Operand">
    <eAnnotations
        source="http://www.eclipse.org/emf/2002/GenModel">
      <details
          key="documentation"
          value="The Constant represents a value, which can be used in Operations."/>
    </eAnnotations>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="value"
        lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations
          source="http://www.eclipse.org/emf/2002/GenModel">
        <details
            key="documentation"
            value="The value of the Constant."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Copy"
      eSuperTypes="#//UnaryOperation">
    <eAnnotations
        source="http://www.eclipse.org/emf/2002/GenModel">
      <details
          key="documentation"
          value="The Copy operation just copies the value of a PmuCounter event to a new TraceEvent. It is mainly used to rename the numbered pmu channels."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="CoreReference">
    <eAnnotations
        source="http://www.eclipse.org/emf/2002/GenModel">
      <details
          key="documentation"
          value="The CoreReference is used to define the containment of a set of CoreTypes in a ClusterType."/>
    </eAnnotations>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="instanceCount"
        lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1">
      <eAnnotations
          source="http://www.eclipse.org/emf/2002/GenModel">
        <details
            key="documentation"
            value="The number of CoreType instances this reference refers to."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="coreType"
        eType="#//CoreType">
      <eAnnotations
          source="http://www.eclipse.org/emf/2002/GenModel">
        <details
            key="documentation"
            value="The CoreType this reference refers to."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="CoreSpecificAnnotations">
    <eAnnotations
        source="http://www.eclipse.org/emf/2002/GenModel">
      <details
          key="documentation"
          value="A list of key-value pairs, which are valid for a specific CoreType."/>
    </eAnnotations>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="coreType"
        eType="#//CoreType"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="annotations"
        upperBound="-1"
        eType="#//platform/StringToStringMapEntry"
        containment="true"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="CoreSpecificTimeDistribution"
      eSuperTypes="#//platform/TimeDistribution">
    <eAnnotations
        source="http://www.eclipse.org/emf/2002/GenModel">
      <details
          key="documentation"
          value="A specialized TimeDistribution valid only for a specific CoreType. "/>
    </eAnnotations>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="coreType"
        eType="#//CoreType">
      <eAnnotations
          source="http://www.eclipse.org/emf/2002/GenModel">
        <details
            key="documentation"
            value="The CoreType for which this time distribution is valid."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="CoreType"
      eSuperTypes="#//TypeDefinition">
    <eAnnotations
        source="http://www.eclipse.org/emf/2002/GenModel">
      <details
          key="documentation"
          value="The CoreType defines the properties of a type of Core. Examples are R52, R52+ or M33."/>
    </eAnnotations>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="frequency"
        lowerBound="1"
        eType="#//platform/Frequency"
        containment="true">
      <eAnnotations
          source="http://www.eclipse.org/emf/2002/GenModel">
        <details
            key="documentation"
            value="The nominal clock frequency of the Core."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="mpuRegionCount"
        lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="16">
      <eAnnotations
          source="http://www.eclipse.org/emf/2002/GenModel">
        <details
            key="documentation"
            value="The number of MPU memory regions that can be defined for the Core."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Divide"
      eSuperTypes="#//BinaryOperation">
    <eAnnotations
        source="http://www.eclipse.org/emf/2002/GenModel">
      <details
          key="documentation"
          value="When evaluated, the Divide Operation evaluates its two Operands and divides the result of the left side Operand by the result of the right side Operand."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="InterferenceImpact"
      eSuperTypes="#//platform/ModelObject">
    <eAnnotations
        source="http://www.eclipse.org/emf/2002/GenModel">
      <details
          key="documentation"
          value="Describes the impact depending on annotations when code runs in parallel"/>
    </eAnnotations>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="operation"
        lowerBound="1"
        eType="#//Operation"
        containment="true"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="InterferenceImpactAnnotation"
      eSuperTypes="#//platform/ModelObject #//Operand">
    <eAnnotations
        source="http://www.eclipse.org/emf/2002/GenModel">
      <details
          key="documentation"
          value="Reference to Annotation of Category"/>
    </eAnnotations>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="annotation"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="InterferenceImpactConfiguration"
      eSuperTypes="#//platform/ModelObject">
    <eAnnotations
        source="http://www.eclipse.org/emf/2002/GenModel">
      <details
          key="documentation"
          value="Describes a set of InterferenceImpacts that are applied during simulation."/>
    </eAnnotations>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="interferenceImpacts"
        upperBound="-1"
        eType="#//InterferenceImpact"
        containment="true"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="InterferenceImpactParallelism"
      eSuperTypes="#//platform/ModelObject #//Operand">
    <eAnnotations
        source="http://www.eclipse.org/emf/2002/GenModel">
      <details
          key="documentation"
          value="Number of cores currently running in parallel"/>
    </eAnnotations>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="Value"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Maximum"
      eSuperTypes="#//BinaryOperation">
    <eAnnotations
        source="http://www.eclipse.org/emf/2002/GenModel">
      <details
          key="documentation"
          value="When evaluated, the Maximum Operation evaluates its two Operands and returns the maximum."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Minimum"
      eSuperTypes="#//BinaryOperation">
    <eAnnotations
        source="http://www.eclipse.org/emf/2002/GenModel">
      <details
          key="documentation"
          value="When evaluated, the Minimum Operation evaluates its two Operands and returns the minimum."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Multiply"
      eSuperTypes="#//BinaryOperation">
    <eAnnotations
        source="http://www.eclipse.org/emf/2002/GenModel">
      <details
          key="documentation"
          value="When evaluated, the Multiply Operation evaluates its two Operands and multiplies the result."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Operand"
      abstract="true">
    <eAnnotations
        source="http://www.eclipse.org/emf/2002/GenModel">
      <details
          key="documentation"
          value="The Operand is an abstract class, which is used in Operations."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Operation"
      abstract="true"
      eSuperTypes="#//Operand">
    <eAnnotations
        source="http://www.eclipse.org/emf/2002/GenModel">
      <details
          key="documentation"
          value="The abstrace class Operation represents either unary or binary operations on Operands."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="OsType"
      eSuperTypes="#//TypeDefinition">
    <eAnnotations
        source="http://www.eclipse.org/emf/2002/GenModel">
      <details
          key="documentation"
          value="The OsType defines abstract properties of an operating system."/>
    </eAnnotations>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="overheads"
        upperBound="-1"
        eType="#//Overhead"
        containment="true">
      <eAnnotations
          source="http://www.eclipse.org/emf/2002/GenModel">
        <details
            key="documentation"
            value="The Overheads the operating system induces for its core operations."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Overhead">
    <eAnnotations
        source="http://www.eclipse.org/emf/2002/GenModel">
      <details
          key="documentation"
          value="The Overhead is produced by an operating system executing on a specific CoreType. It includes context switch times and interrupt entry and exit latencies."/>
    </eAnnotations>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="overheadType"
        lowerBound="1"
        eType="#//OverheadType"
        defaultValueLiteral="Unspecified">
      <eAnnotations
          source="http://www.eclipse.org/emf/2002/GenModel">
        <details
            key="documentation"
            value="The type of overhead, e.g. interrupt entry latency."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="timeDistributions"
        lowerBound="1"
        upperBound="-1"
        eType="#//CoreSpecificTimeDistribution"
        containment="true">
      <eAnnotations
          source="http://www.eclipse.org/emf/2002/GenModel">
        <details
            key="documentation"
            value="A set of CoreType specific TimeDistributions, that defines the net execution time of this Overhead."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EEnum"
      name="OverheadType">
    <eAnnotations
        source="http://www.eclipse.org/emf/2002/GenModel">
      <details
          key="documentation"
          value="The type of an Overhead."/>
    </eAnnotations>
    <eLiterals
        name="Unspecified">
      <eAnnotations
          source="http://www.eclipse.org/emf/2002/GenModel">
        <details
            key="documentation"
            value="The default type Unspecified does not represent a specific overhead."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals
        name="IsrEntry"
        value="1">
      <eAnnotations
          source="http://www.eclipse.org/emf/2002/GenModel">
        <details
            key="documentation"
            value="Latency from the raising of an interrupt to the first instruction of the specified interrupt service routine."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals
        name="IsrExit"
        value="2">
      <eAnnotations
          source="http://www.eclipse.org/emf/2002/GenModel">
        <details
            key="documentation"
            value="Latency from the end of an interrupt service routine to the resumption of the interrupted function."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals
        name="Cat1IsrEntry"
        value="3">
      <eAnnotations
          source="http://www.eclipse.org/emf/2002/GenModel">
        <details
            key="documentation"
            value="Additional overhead added by the operating system as a set of instructions that is executed at start of a category 1 ISR."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals
        name="Cat1IsrExit"
        value="4">
      <eAnnotations
          source="http://www.eclipse.org/emf/2002/GenModel">
        <details
            key="documentation"
            value="Additional overhead added by the operating system as a set of instructions that is executed at end of a category 1 ISR."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals
        name="Cat2IsrEntry"
        value="5"
        literal="Cat2IsrEntry">
      <eAnnotations
          source="http://www.eclipse.org/emf/2002/GenModel">
        <details
            key="documentation"
            value="Additional overhead added by the operating system as a set of instructions that is executed at start of a category 2 ISR."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals
        name="Cat2IsrExit"
        value="6">
      <eAnnotations
          source="http://www.eclipse.org/emf/2002/GenModel">
        <details
            key="documentation"
            value="Additional overhead added by the operating system as a set of instructions that is executed at start of a category 2 ISR."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals
        name="ContextSwitch"
        value="7">
      <eAnnotations
          source="http://www.eclipse.org/emf/2002/GenModel">
        <details
            key="documentation"
            value="The duration of a basic context switch, only saving and restoring registers."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals
        name="MpuSwitch"
        value="8">
      <eAnnotations
          source="http://www.eclipse.org/emf/2002/GenModel">
        <details
            key="documentation"
            value="The additional overhead added to a ContextSwitch by changing just the access permissions (flags) of one set of MPU registers, not the offset or the size."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals
        name="MpuReconfiguration"
        value="9">
      <eAnnotations
          source="http://www.eclipse.org/emf/2002/GenModel">
        <details
            key="documentation"
            value="The additional overhead added to a ContextSwitch by reconfiguring one set of MPU registers completly."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals
        name="RegisterSecurity"
        value="10">
      <eAnnotations
          source="http://www.eclipse.org/emf/2002/GenModel">
        <details
            key="documentation"
            value="The additional overhead added to a ContextSwitch, when registers need to be nulled for security reasons."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals
        name="VirtualCoreSwitch"
        value="11">
      <eAnnotations
          source="http://www.eclipse.org/emf/2002/GenModel">
        <details
            key="documentation"
            value="The overhead added to a ContextSwitch, if the context changes between different virtual machines."/>
      </eAnnotations>
    </eLiterals>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="PmuCounter"
      eSuperTypes="#//platform/ModelObject #//Operand">
    <eAnnotations
        source="http://www.eclipse.org/emf/2002/GenModel">
      <details
          key="documentation"
          value="A PmuCounter references a TraceEvent, which represents the reading of PMU counter instance."/>
    </eAnnotations>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="counter"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations
          source="http://www.eclipse.org/emf/2002/GenModel">
        <details
            key="documentation"
            value="The reference string of the TraceEvent. The actual instance of the TraceEvent is found by resolving the string similar to a cross document reference."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="PmuOperation"
      eSuperTypes="#//platform/ModelObject">
    <eAnnotations
        source="http://www.eclipse.org/emf/2002/GenModel">
      <details
          key="documentation"
          value="The PmuOperation contains an Operation tree, which is evaluated to combine on or more PmuCounter values into a new TraceEvent value."/>
    </eAnnotations>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="eventName"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations
          source="http://www.eclipse.org/emf/2002/GenModel">
        <details
            key="documentation"
            value="The name of the new TraceEvent, which is created and calculated by this PmuOperation."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="container"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations
          source="http://www.eclipse.org/emf/2002/GenModel">
        <details
            key="documentation"
            value="The reference string of the container. The actual instance of the container element is found by resolving the string similar to a cross document reference. It is only used, when perExecutable is not set.&#xA;For real use, the container must have an EStructuralFeature 'traceEvents', which can contain 0..* TraceEvents."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="operation"
        lowerBound="1"
        eType="#//Operation"
        containment="true">
      <eAnnotations
          source="http://www.eclipse.org/emf/2002/GenModel">
        <details
            key="documentation"
            value="The starting point of the Operation tree."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="perExecutable"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true">
      <eAnnotations
          source="http://www.eclipse.org/emf/2002/GenModel">
        <details
            key="documentation"
            value="When set, the new Event is created per Process or Function, where PMU Events referenced by the Operands occur. The referenced container is not used then."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="RuleSetParam">
    <eAnnotations
        source="http://www.eclipse.org/emf/2002/GenModel">
      <details
          key="documentation"
          value="A set of correction values, which are used by a trace processor for sequences which relate to the given overhead type."/>
    </eAnnotations>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="overheadType"
        eType="#//OverheadType"
        defaultValueLiteral="Unspecified"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="overhead"
        eType="#//platform/Time"
        containment="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="ratio"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="0.5"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Subtract"
      eSuperTypes="#//BinaryOperation">
    <eAnnotations
        source="http://www.eclipse.org/emf/2002/GenModel">
      <details
          key="documentation"
          value="When evaluated, the Subtract Operation evaluates its two Operands and subtracts the result of the right side Operand from the result of the left side Operand."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="TracingTool"
      eSuperTypes="#//platform/ModelObject">
    <eAnnotations
        source="http://www.eclipse.org/emf/2002/GenModel">
      <details
          key="documentation"
          value="The parameter set of a trace processor, which belongs to the give OsType and CoreType, and modifies the trace according to a referenced rule set and the given rule set parameters."/>
    </eAnnotations>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="osType"
        eType="#//OsType"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="coreType"
        eType="#//CoreType"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="ruleSet"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="ruleSetParams"
        upperBound="-1"
        eType="#//RuleSetParam"
        containment="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="glitchThreshold"
        lowerBound="1"
        eType="#//platform/Time"
        containment="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="pmuOperations"
        upperBound="-1"
        eType="#//PmuOperation"
        containment="true">
      <eAnnotations
          source="http://www.eclipse.org/emf/2002/GenModel">
        <details
            key="documentation"
            value="The list of PmuOperations, which are used to combine one or more PmuCounters into new TraceEvent values."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="TypeDefinition"
      abstract="true"
      eSuperTypes="#//platform/ModelObject">
    <eAnnotations
        source="http://www.eclipse.org/emf/2002/GenModel">
      <details
          key="documentation"
          value="An abstract base class for all type definitions: ClusterType, CoreType and OsType. All TypeDefinitions are contained in Library."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="UnaryOperation"
      abstract="true"
      eSuperTypes="#//Operation">
    <eAnnotations
        source="http://www.eclipse.org/emf/2002/GenModel">
      <details
          key="documentation"
          value="The UnaryOperation is an abstract class, which represents an Operation with a single Operand."/>
    </eAnnotations>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="operand"
        lowerBound="1"
        eType="#//Operand"
        containment="true">
      <eAnnotations
          source="http://www.eclipse.org/emf/2002/GenModel">
        <details
            key="documentation"
            value="The Operand used on the left side of the Operation."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eSubpackages
      name="platform"
      nsURI="http://inchron.com/callisto/0.1.0"
      nsPrefix="platform">
    <eClassifiers
        xsi:type="ecore:EClass"
        name="DiscreteDistributionEntry">
      <eAnnotations
          source="http://www.eclipse.org/emf/2002/GenModel">
        <details
            key="documentation"
            value="A DiscreteDistributionEntry as part of the definition of a discrete TimeDistribution describes the number of Time values that are expected to be within a certain time interval, based on the total number in all entries of the TimeDistribution definition."/>
      </eAnnotations>
      <eStructuralFeatures
          xsi:type="ecore:EAttribute"
          name="count"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"
          defaultValueLiteral="1">
        <eAnnotations
            source="http://www.eclipse.org/emf/2002/GenModel">
          <details
              key="documentation"
              value="The number of Time values that are expected to be within the boundaries of lower and upper. Must be greater than zero. The propability equals this number divided by the total number over all entries. "/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures
          xsi:type="ecore:EReference"
          name="lower"
          lowerBound="1"
          eType="#//platform/Time"
          containment="true">
        <eAnnotations
            source="http://www.eclipse.org/emf/2002/GenModel">
          <details
              key="documentation"
              value="The lower bound of the time interval described by this DiscreteDistributionEntry."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures
          xsi:type="ecore:EReference"
          name="upper"
          lowerBound="1"
          eType="#//platform/Time"
          containment="true">
        <eAnnotations
            source="http://www.eclipse.org/emf/2002/GenModel">
          <details
              key="documentation"
              value="The upper bound of the time interval described by this DiscreteDistributionEntry."/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers
        xsi:type="ecore:EClass"
        name="Frequency">
      <eAnnotations
          source="http://www.eclipse.org/emf/2002/GenModel">
        <details
            key="documentation"
            value="A Frequency is a physical quantity to measure the number of occurrences of a repeating event per unit of time defined by a numerical value and a unit."/>
      </eAnnotations>
      <eStructuralFeatures
          xsi:type="ecore:EAttribute"
          name="value"
          lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
          defaultValueLiteral="1000">
        <eAnnotations
            source="http://www.eclipse.org/emf/2002/GenModel">
          <details
              key="documentation"
              value="The numerical value of the quantity."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures
          xsi:type="ecore:EAttribute"
          name="unit"
          lowerBound="1"
          eType="#//platform/FrequencyUnit"
          defaultValueLiteral="MHz">
        <eAnnotations
            source="http://www.eclipse.org/emf/2002/GenModel">
          <details
              key="documentation"
              value="The unit of the quantity."/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers
        xsi:type="ecore:EEnum"
        name="FrequencyUnit">
      <eAnnotations
          source="http://www.eclipse.org/emf/2002/GenModel">
        <details
            key="documentation"
            value="This enumeration is used to define the possible units of a Frequency quantity."/>
      </eAnnotations>
      <eLiterals
          name="Hz">
        <eAnnotations
            source="http://www.eclipse.org/emf/2002/GenModel">
          <details
              key="documentation"
              value="Hertz."/>
        </eAnnotations>
      </eLiterals>
      <eLiterals
          name="kHz"
          value="1">
        <eAnnotations
            source="http://www.eclipse.org/emf/2002/GenModel">
          <details
              key="documentation"
              value="Kilohertz = 1000 Hertz."/>
        </eAnnotations>
      </eLiterals>
      <eLiterals
          name="MHz"
          value="2">
        <eAnnotations
            source="http://www.eclipse.org/emf/2002/GenModel">
          <details
              key="documentation"
              value="Megahertz = 1000^2 Hertz."/>
        </eAnnotations>
      </eLiterals>
      <eLiterals
          name="GHz"
          value="3">
        <eAnnotations
            source="http://www.eclipse.org/emf/2002/GenModel">
          <details
              key="documentation"
              value="Gigahertz = 1000^3 Hertz."/>
        </eAnnotations>
      </eLiterals>
    </eClassifiers>
    <eClassifiers
        xsi:type="ecore:EClass"
        name="ModelObject"
        abstract="true">
      <eAnnotations
          source="http://www.eclipse.org/emf/2002/GenModel">
        <details
            key="documentation"
            value="The abstract base class for identifiable, named model entities. The ID attribute 'intrinsicId' can be used as reference instead of a xpath. To this end, the attribute must be initialized with a Globally Unique Identifier (GUID)."/>
      </eAnnotations>
      <eStructuralFeatures
          xsi:type="ecore:EAttribute"
          name="comment"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations
            source="http://www.eclipse.org/emf/2002/GenModel">
          <details
              key="documentation"
              value="A comment on this ModelObject. It has no semantic significance for the model."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures
          xsi:type="ecore:EAttribute"
          name="intrinsicId"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          iD="true"/>
      <eStructuralFeatures
          xsi:type="ecore:EAttribute"
          name="name"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations
            source="http://www.eclipse.org/emf/2002/GenModel">
          <details
              key="documentation"
              value="The name of this ModelObject."/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers
        xsi:type="ecore:EClass"
        name="StringToStringMapEntry">
      <eAnnotations
          source="http://www.eclipse.org/emf/2002/GenModel">
        <details
            key="documentation"
            value="This class represents a key value string pair and can be used in a map like container."/>
      </eAnnotations>
      <eStructuralFeatures
          xsi:type="ecore:EAttribute"
          name="key"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures
          xsi:type="ecore:EAttribute"
          name="value"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers
        xsi:type="ecore:EClass"
        name="Time">
      <eAnnotations
          source="http://www.eclipse.org/emf/2002/GenModel">
        <details
            key="documentation"
            value="A physical time quantity."/>
      </eAnnotations>
      <eOperations
          name="denormalize">
        <eAnnotations
            source="http://www.eclipse.org/emf/2002/GenModel">
          <details
              key="documentation"
              value="For most operations the value field of a Time object is normalized to a specific TimeUnit. This functon denormalizes the value and the unit, so that it uses the largest TimeUnit, which is possible without a precision loss."/>
        </eAnnotations>
      </eOperations>
      <eStructuralFeatures
          xsi:type="ecore:EAttribute"
          name="value"
          lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"
          defaultValueLiteral="0">
        <eAnnotations
            source="http://www.eclipse.org/emf/2002/GenModel">
          <details
              key="documentation"
              value="The numerical time value."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures
          xsi:type="ecore:EAttribute"
          name="unit"
          lowerBound="1"
          eType="#//platform/TimeUnit"
          defaultValueLiteral="ps">
        <eAnnotations
            source="http://www.eclipse.org/emf/2002/GenModel">
          <details
              key="documentation"
              value="The time unit."/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers
        xsi:type="ecore:EClass"
        name="TimeDistribution">
      <eAnnotations
          source="http://www.eclipse.org/emf/2002/GenModel">
        <details
            key="documentation"
            value="This class is used to define a distribution for a random variable of type Time."/>
      </eAnnotations>
      <eStructuralFeatures
          xsi:type="ecore:EReference"
          name="min"
          lowerBound="1"
          eType="#//platform/Time"
          containment="true">
        <eAnnotations
            source="http://www.eclipse.org/emf/2002/GenModel">
          <details
              key="documentation"
              value="The lower bound of this distribution."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures
          xsi:type="ecore:EReference"
          name="max"
          lowerBound="1"
          eType="#//platform/Time"
          containment="true">
        <eAnnotations
            source="http://www.eclipse.org/emf/2002/GenModel">
          <details
              key="documentation"
              value="The upper bound of this distribution."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures
          xsi:type="ecore:EReference"
          name="mean"
          lowerBound="1"
          eType="#//platform/Time"
          containment="true">
        <eAnnotations
            source="http://www.eclipse.org/emf/2002/GenModel">
          <details
              key="documentation"
              value="The mean value in this distribution."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures
          xsi:type="ecore:EReference"
          name="sigma"
          lowerBound="1"
          eType="#//platform/Time"
          containment="true">
        <eAnnotations
            source="http://www.eclipse.org/emf/2002/GenModel">
          <details
              key="documentation"
              value="The standard deviation parameter of the normal distribution."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures
          xsi:type="ecore:EAttribute"
          name="alpha"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
          defaultValueLiteral="1.0">
        <eAnnotations
            source="http://www.eclipse.org/emf/2002/GenModel">
          <details
              key="documentation"
              value="Alpha is used for the Beta distribution and for the Weibull distribution, where it represents the shape parameter k."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures
          xsi:type="ecore:EAttribute"
          name="beta"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
          defaultValueLiteral="1.0">
        <eAnnotations
            source="http://www.eclipse.org/emf/2002/GenModel">
          <details
              key="documentation"
              value="Beta is used for the Beta distribution and for the Weibull distribution, where it represents the scale parameter beta (which equals 1 divided by λ)."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures
          xsi:type="ecore:EAttribute"
          name="outlierProbability"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
          defaultValueLiteral="0.001">
        <eAnnotations
            source="http://www.eclipse.org/emf/2002/GenModel">
          <details
              key="documentation"
              value="The outlierProbability (0 &lt; outlierProbability &lt; 1) is used for the WeibullEstimator distribution, where it represents the probability that a rolled value is greater than max. Note that a high outlierProbability can lead to excessive simulation times due to the repeated rolling of outliers."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures
          xsi:type="ecore:EReference"
          name="discreteDistribution"
          upperBound="-1"
          eType="#//platform/DiscreteDistributionEntry"
          containment="true">
        <eAnnotations
            source="http://www.eclipse.org/emf/2002/GenModel">
          <details
              key="documentation"
              value="A discrete distribution defined as a list of DiscreteDistributionEntry objects."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures
          xsi:type="ecore:EAttribute"
          name="type"
          lowerBound="1"
          eType="#//platform/TimeDistributionType"
          defaultValueLiteral="Max">
        <eAnnotations
            source="http://www.eclipse.org/emf/2002/GenModel">
          <details
              key="documentation"
              value="The distribution type."/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers
        xsi:type="ecore:EEnum"
        name="TimeDistributionType">
      <eAnnotations
          source="http://www.eclipse.org/emf/2002/GenModel">
        <details
            key="documentation"
            value="This enumeration defines the types that can be set for a TimeDistribution."/>
      </eAnnotations>
      <eLiterals
          name="Min"
          literal="Min">
        <eAnnotations
            source="http://www.eclipse.org/emf/2002/GenModel">
          <details
              key="documentation"
              value="The constant value min is used."/>
        </eAnnotations>
      </eLiterals>
      <eLiterals
          name="Max"
          value="1"
          literal="Max">
        <eAnnotations
            source="http://www.eclipse.org/emf/2002/GenModel">
          <details
              key="documentation"
              value="The constant value max is used."/>
        </eAnnotations>
      </eLiterals>
      <eLiterals
          name="Mean"
          value="2">
        <eAnnotations
            source="http://www.eclipse.org/emf/2002/GenModel">
          <details
              key="documentation"
              value="The constant value mean is used."/>
        </eAnnotations>
      </eLiterals>
      <eLiterals
          name="Uniform"
          value="3">
        <eAnnotations
            source="http://www.eclipse.org/emf/2002/GenModel">
          <details
              key="documentation"
              value="A uniform distribution between min and max is used."/>
        </eAnnotations>
      </eLiterals>
      <eLiterals
          name="Normal"
          value="4">
        <eAnnotations
            source="http://www.eclipse.org/emf/2002/GenModel">
          <details
              key="documentation"
              value="The normal distribution, as characterized by mean and sigma, is used. The value is additionally limited between min and max."/>
        </eAnnotations>
      </eLiterals>
      <eLiterals
          name="Weibull"
          value="5"
          literal="Weibull">
        <eAnnotations
            source="http://www.eclipse.org/emf/2002/GenModel">
          <details
              key="documentation"
              value="The timing is based on a Weibull distribution with the shape parameter alpha and the scale parameter beta (equals 1 divided by λ), limited by min and max."/>
        </eAnnotations>
      </eLiterals>
      <eLiterals
          name="WeibullEstimator"
          value="6">
        <eAnnotations
            source="http://www.eclipse.org/emf/2002/GenModel">
          <details
              key="documentation"
              value="The timing is based on a Weibull distribution parameterized by min (lower bound), max (upper bound), mean, and an outlierProbability (0 &lt; outlierProbability &lt; 1) which is the probability that a rolled value is greater than max. Note that a high outlierProbability can lead to excessive simulation times due to the repeated rolling of outliers."/>
        </eAnnotations>
      </eLiterals>
      <eLiterals
          name="Discrete"
          value="7"
          literal="Discrete">
        <eAnnotations
            source="http://www.eclipse.org/emf/2002/GenModel">
          <details
              key="documentation"
              value="The timing is based on a discrete distribution as given by the list of DiscreteDistributionEntrys."/>
        </eAnnotations>
      </eLiterals>
      <eLiterals
          name="Beta"
          value="8"
          literal="Beta">
        <eAnnotations
            source="http://www.eclipse.org/emf/2002/GenModel">
          <details
              key="documentation"
              value="The timing is based on a Beta distribution, as defined by the parameters alpha and beta, limited by min and max."/>
        </eAnnotations>
      </eLiterals>
      <eLiterals
          name="BestCase"
          value="9"
          literal="BestCase">
        <eAnnotations
            source="http://www.eclipse.org/emf/2002/GenModel">
          <details
              key="documentation"
              value="The timing is based on a Beta distribution with alpha=0.2 and beta=1.0, limited by min and max."/>
        </eAnnotations>
      </eLiterals>
      <eLiterals
          name="WorstCase"
          value="10"
          literal="WorstCase">
        <eAnnotations
            source="http://www.eclipse.org/emf/2002/GenModel">
          <details
              key="documentation"
              value="The timing is based on a Beta distribution with alpha=1.0 and beta=0.2, limited by min and max."/>
        </eAnnotations>
      </eLiterals>
      <eLiterals
          name="AverageCase"
          value="11"
          literal="AverageCase">
        <eAnnotations
            source="http://www.eclipse.org/emf/2002/GenModel">
          <details
              key="documentation"
              value="The timing is based on a Beta distribution with alpha=2.0 and beta=2.0, limited by min and max."/>
        </eAnnotations>
      </eLiterals>
      <eLiterals
          name="CornerCase"
          value="12"
          literal="CornerCase">
        <eAnnotations
            source="http://www.eclipse.org/emf/2002/GenModel">
          <details
              key="documentation"
              value="The timing is based on a Beta distribution with alpha=0.2 and beta=0.2, limited by min and max."/>
        </eAnnotations>
      </eLiterals>
    </eClassifiers>
    <eClassifiers
        xsi:type="ecore:EEnum"
        name="TimeUnit">
      <eAnnotations
          source="http://www.eclipse.org/emf/2002/GenModel">
        <details
            key="documentation"
            value="This enumeration is used to define the possible units of a Time quantity."/>
      </eAnnotations>
      <eLiterals
          name="s">
        <eAnnotations
            source="http://www.eclipse.org/emf/2002/GenModel">
          <details
              key="documentation"
              value="Seconds."/>
        </eAnnotations>
      </eLiterals>
      <eLiterals
          name="ms"
          value="1">
        <eAnnotations
            source="http://www.eclipse.org/emf/2002/GenModel">
          <details
              key="documentation"
              value="Milliseconds."/>
        </eAnnotations>
      </eLiterals>
      <eLiterals
          name="us"
          value="2">
        <eAnnotations
            source="http://www.eclipse.org/emf/2002/GenModel">
          <details
              key="documentation"
              value="Microseconds."/>
        </eAnnotations>
      </eLiterals>
      <eLiterals
          name="ns"
          value="3">
        <eAnnotations
            source="http://www.eclipse.org/emf/2002/GenModel">
          <details
              key="documentation"
              value="Nanoseconds."/>
        </eAnnotations>
      </eLiterals>
      <eLiterals
          name="ps"
          value="4">
        <eAnnotations
            source="http://www.eclipse.org/emf/2002/GenModel">
          <details
              key="documentation"
              value="Picoseconds."/>
        </eAnnotations>
      </eLiterals>
      <eLiterals
          name="fs"
          value="5">
        <eAnnotations
            source="http://www.eclipse.org/emf/2002/GenModel">
          <details
              key="documentation"
              value="Femtoseconds."/>
        </eAnnotations>
      </eLiterals>
      <eLiterals
          name="T"
          value="6">
        <eAnnotations
            source="http://www.eclipse.org/emf/2002/GenModel">
          <details
              key="documentation"
              value="Ticks, depending on a Clock."/>
        </eAnnotations>
      </eLiterals>
      <eLiterals
          name="NaN"
          value="7"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
